kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-initdb-pv-volume
  labels:
    type: local
    app: postgresql
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /host_mnt/c/develop/springboot-sakila-jpa/postgresql/init_db/sql
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-initdb-pv-claim
  labels:
    app: postgresql
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi