kind: Secret
apiVersion: v1
metadata:
  name: pgsql-connection-secret
data:
  password: czNoZlVORGFnYg==
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-jpa
  labels:
    app: springboot
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: springboot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot-jpa
        image: aballaci/springboot-sakila-jpa:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: PGSQL_HOST
            value: postgres-postgresql
          - name: PGSQL_USER
            value: "postgres"
          - name: PGSQL_PORT
            value: "5432"
          - name: PGSQL_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: pgsql-connection-secret
                  key: password
        ports:
        - containerPort: 8080
